In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from datetime import datetime, timedelta
import seaborn as sn
import time

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

Выделяем только тех, у кого был контакт, начиная с 13 мая

In [ ]:
df = df[(df['mkb10_code'] == 'Z20.8') & (df['dis_date'] >= '2020-05-13')]
df['idx'].unique()
Contact = df['idx'].unique()

Подтвержденный U07.2

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Contact)]

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2') & (df['dis_date'] >= '2020-05-13')]

In [ ]:
df.shape

(5204, 17)

In [ ]:
pd.DataFrame(df['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Illness2.xlsx')

In [ ]:
Illness2 = df['idx'].unique()
Illness2

array([    164,     427,     569, ..., 1260183, 1266796, 1274932])

Acute_illness2, все из списка *Illness2*, у кого есть IgM > 1

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Illness2)]

In [ ]:
df = df[df['IgM'] > 1]

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2')]

In [ ]:
df

            idx    pd_id  ...  samples_result_id                mu_type
428         164  1621174  ...                NaN  ��������� �����������
4204       1517  2761582  ...                NaN  ��������� �����������
12559      4139  3129070  ...                NaN  ��������� �����������
13072      4320  1560202  ...                NaN  ��������� �����������
18371      6211  1523632  ...                NaN  ��������� �����������
...         ...      ...  ...                ...                    ...
1334531  531006  4222011  ...                NaN     ��������� ��������
1337101  532518  4234800  ...                NaN  ��������� �����������
1346981  537808  4219602  ...                NaN  ��������� �����������
1347657  538238  4213171  ...                NaN  ��������� �����������
1350977  540283  4269331  ...                NaN     ��������� ��������

[1003 rows x 17 columns]

In [ ]:
pd.DataFrame(df['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Acute_illness2.xlsx')

In [ ]:
Acute_illness2 =  df['idx'].unique()

In [ ]:
Acute_illness2

array([   164,   1517,   4139,   4320,   6211,   6559,   8883,   9150,
        10394,  10874,  12402,  12403,  12480,  14563,  14862,  14918,
        15281,  15383,  16840,  17895,  17981,  18000,  19436,  20265,
        20455,  21871,  22907,  23008,  23071,  23324,  23637,  23865,
        24713,  25239,  25613,  26810,  26957,  27270,  28382,  29460,
        30386,  31622,  32780,  33178,  33474,  33667,  33914,  33928,
        34025,  34235,  35529,  35633,  35678,  35875,  37250,  37660,
        37838,  38767,  39699,  39736,  39924,  39958,  40357,  40505,
        41701,  42726,  42754,  43633,  44220,  44248,  44315,  47875,
        48519,  48838,  49880,  50158,  50459,  50596,  51450,  52055,
        53994,  54400,  55579,  55732,  57263,  57302,  57362,  61626,
        62128,  64219,  64224,  66734,  70147,  72614,  73753,  73951,
        74663,  74752,  74951,  75181,  75298,  76087,  76221,  77554,
        79950,  81373,  81604,  82787,  83438,  84565,  84683,  84991,
        85131,  85194,  85223,  85838,  87520,  87564,  87587,  88074,
        88262,  88988,  89278,  89763,  90861,  90923,  91331,  92471,
        92593,  92718,  92904,  93765,  94002,  95556,  95902,  96289,
        96470,  96557,  96571,  96726,  97024,  97600,  97938,  98077,
        98238,  98239,  98240,  98432,  98680,  98688,  98742,  98858,
        98886,  99698,  99979, 100587, 101717, 101786, 102745, 103228,
       103238, 103744, 103808, 103834, 105466, 105477, 106685, 108532,
       108806, 108870, 109654, 109760, 110060, 110089, 110250, 110376,
       110611, 112724, 112988, 113607, 113894, 113897, 114046, 115538,
       115601, 116153, 118281, 119181, 121801, 122371, 123277, 124992,
       125431, 125945, 126952, 128368, 131596, 131878, 132248, 133336,
       133477, 133776, 134050, 134363, 134503, 134685, 134690, 135101,
       135656, 136641, 136816, 137012, 137094, 138081, 141264, 141834,
       141863, 142807, 143193, 143287, 143668, 143725, 143845, 144995,
       145652, 145985, 146926, 147475, 147495, 147518, 147578, 147596,
       147623, 147629, 147637, 147648, 147650, 147744, 147752, 147776,
       147983, 148005, 148028, 149348, 149718, 150796, 151147, 151217,
       151278, 152430, 153453, 153470, 153480, 153543, 153604, 153662,
       153814, 153842, 153869, 154298, 154630, 155773, 155784, 155804,
       155809, 157788, 157882, 157898, 157903, 157905, 157920, 157942,
       157949, 158269, 158300, 158312, 158348, 158365, 158412, 158567,
       158672, 158903, 159359, 159575, 160445, 161007, 161189, 161204,
       161367, 161652, 162200, 162232, 162259, 162669, 163417, 163788,
       163809, 163810, 163829, 164082, 164128, 164285, 164379, 165970,
       166613, 168728, 169632, 169669, 169738, 169768, 169769, 169796,
       169798, 170547, 170771, 170859, 170869, 171178, 171430, 171558,
       172248, 172279, 172316, 172767, 174164, 174165, 174634, 175390,
       176482, 176636, 176655, 177846, 179126, 179199, 179363, 179566,
       179581, 180905, 181609, 183254, 183914, 185001, 186116, 186225,
       186226, 186259, 186269, 186297, 189246, 189255, 191798, 193588,
       193919, 194478, 194833, 194912, 194963, 196797, 199020, 199960,
       200043, 200126, 200132, 201960, 202029, 202031, 202135, 202402,
       203245, 203264, 203347, 203351, 205334, 205914, 206676, 208603,
       208621, 209434, 209993, 211077, 211310, 211628, 211651, 212895,
       212983, 213082, 213164, 213471, 213494, 213516, 213531, 213573,
       213574, 213578, 213579, 213596, 213622, 213655, 213700, 213909,
       213953, 214237, 214400, 215643, 215647, 215654, 215662, 216610,
       216612, 216613, 216615, 217088, 217091, 217106, 217221, 217374,
       217496, 217857, 217875, 217909, 219054, 219817, 220220, 220339,
       220968, 221014, 221302, 222502, 223250, 223313, 223607, 224932,
       224999, 225518, 225627, 225672, 226651, 227036, 227659, 227813,
       228056, 228280, 229110, 232242, 233532, 233608, 233792, 234674,
       235587, 236302, 236815, 237346, 238199, 238466, 239117, 239124,
       239125, 240347, 240494, 241474, 242182, 243885, 244261, 244262,
       244287, 247566, 247781, 248147, 248346, 248444, 249397, 249683,
       249949, 250017, 250173, 250541, 250891, 251003, 251037, 252032,
       253140, 253834, 254121, 254189, 254349, 254444, 254645, 254682,
       254857, 254886, 254898, 254906, 254912, 255026, 256200, 257029,
       257756, 259070, 259777, 260175, 260398, 260945, 262620, 262639,
       262640, 263616, 263815, 267543, 267597, 267874, 269986, 269988,
       269989, 270167, 270610, 271177, 271716, 271995, 272330, 272734,
       272859, 273252, 273439, 274912, 276229, 277944, 278510, 278568,
       278837, 279325, 280310, 280403, 281275, 281865, 284465, 284497,
       284533, 284812, 285118, 285806, 287794, 289014, 289811, 292498,
       292558, 292693, 293548, 293579, 293768, 295093, 295156, 295643,
       295644, 296144, 296585, 298152, 298284, 298511, 298566, 298605,
       298619, 298684, 299481, 299720, 299947, 300332, 301630, 301653,
       302550, 302562, 302577, 302580, 302838, 303757, 303915, 303917,
       304721, 305728, 305732, 305790, 306406, 306703, 308122, 308171,
       309695, 309745, 309756, 309818, 311608, 312617, 312627, 313566,
       314480, 316949, 316953, 319870, 319897, 320104, 321134, 321478,
       324276, 324501, 327697, 327876, 327880, 328574, 330150, 332492,
       333369, 333699, 333723, 333781, 333809, 334106, 334519, 334603,
       335993, 336018, 336019, 336113, 336130, 336131, 336182, 336221,
       336672, 337223, 337290, 337478, 337983, 338325, 338735, 340061,
       341486, 341586, 342384, 342653, 342698, 343331, 344494, 344915,
       345204, 345285, 346295, 346442, 346511, 346515, 346522, 348428,
       348647, 348702, 349645, 349870, 351338, 351712, 351905, 352059,
       352176, 355739, 356371, 356508, 357375, 358770, 358953, 359047,
       359159, 359996, 363240, 363287, 363374, 363796, 364641, 364673,
       365964, 368356, 368773, 369377, 369785, 370740, 371288, 371609,
       371881, 373567, 373942, 375493, 375562, 375580, 375636, 375943,
       378372, 379195, 379487, 385542, 385744, 386195, 386619, 387149,
       387179, 387485, 388088, 388111, 388221, 388268, 389771, 392335,
       393584, 393849, 395912, 396136, 396589, 396979, 398102, 399993,
       400385, 402522, 402701, 403371, 403710, 405417, 407697, 407756,
       407826, 408151, 412073, 413512, 417728, 419284, 420145, 420146,
       421454, 422182, 422389, 425815, 426369, 426776, 426846, 431173,
       431577, 431973, 432126, 432275, 433152, 435493, 435772, 436184,
       436719, 437022, 437420, 437896, 438229, 443550, 445555, 452257,
       452790, 455310, 457315, 458969, 460612, 460720, 465106, 465107,
       476929, 477176, 480495, 485693, 491041, 492041, 493523, 495292,
       495789, 497598, 500261, 500279, 500937, 501057, 501384, 502271,
       502565, 504517, 504792, 507408, 509058, 511971, 514056, 517552,
       523492, 524559, 524772, 524773, 529985, 531006, 532518, 537808,
       538238, 540283])

Immun_memory2, все из списка Acute_illness2, у кого тест на имунную память позже положителен, чем на острую инфекцию

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Acute_illness2)]

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2')]

In [ ]:
df

            idx    pd_id  ...  samples_result_id                mu_type
428         164  1621174  ...                NaN  ��������� �����������
4204       1517  2761582  ...                NaN  ��������� �����������
12559      4139  3129070  ...                NaN  ��������� �����������
13072      4320  1560202  ...                NaN  ��������� �����������
18371      6211  1523632  ...                NaN  ��������� �����������
...         ...      ...  ...                ...                    ...
1334533  531006  3946782  ...      �� ����������     ��������� ��������
1337101  532518  4234800  ...                NaN  ��������� �����������
1346981  537808  4219602  ...                NaN  ��������� �����������
1347657  538238  4213171  ...                NaN  ��������� �����������
1350977  540283  4269331  ...                NaN     ��������� ��������

[1706 rows x 17 columns]

In [ ]:
Immun_memory2 = pd.DataFrame(Acute_illness2, columns=['idx'])

In [ ]:
def ImmGM ( idx ):
  return min(np.hstack([df[(df['idx'] == idx) & (df['IgM'] < 1) & (df['IgG'] > 10)]['get_date_at'], '2050-01-01']))

In [ ]:
def ImmM ( idx ):
  return min(np.hstack([df[(df['idx'] == idx) & (df['IgM'] > 1)]['get_date_at'], '2050-01-01']))

In [ ]:
#np.vectorize(ImmM)(Immun_memory2['idx'])

In [ ]:
#Когда тест IgM был > 1
Immun_memory2['test_day_M'] = np.vectorize(ImmM)(Immun_memory2['idx'])

In [ ]:
#Когда тест IgM < 1 & IgG > 10
Immun_memory2['test_day_G_M'] = np.vectorize(ImmGM)(Immun_memory2['idx'])

In [ ]:
Immun_memory2 = Immun_memory2[Immun_memory2['test_day_G_M'] != '2050-01-01']

In [ ]:
Immun_memory2 = Immun_memory2[Immun_memory2['test_day_G_M'] > Immun_memory2['test_day_M']]
Immun_memory2

        idx  test_day_M test_day_G_M
299  164082  2020-05-27   2020-06-07
324  174164  2020-06-04   2020-06-09
404  215647  2020-06-03   2020-06-16

In [ ]:
pd.DataFrame(Immun_memory2['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Immun_memory2.xlsx')

No_immun_memory, нет иммунной памяти после перенесенного заболевания
 *(второй или теретий диагноз  IgM<1, IgG<10)*

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Acute_illness2)]

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2')]

In [ ]:
def ImmM ( idx ):
  return min(df[(df['idx'] == idx) & (df['IgM'] > 1)]['get_date_at'])

In [ ]:
np.vectorize(ImmM)(Immun_memory2['idx'])

array(['2020-05-27', '2020-06-04', '2020-06-03'], dtype='<U10')

In [ ]:
No_immun_memory2 = pd.DataFrame(Acute_illness2, columns=['idx'])

In [ ]:
#Когда тест IgM был > 1
No_immun_memory2['test_day_M'] = np.vectorize(ImmM)(No_immun_memory2['idx'])

In [ ]:
def ImmGM_no ( idx ):
  return min(np.hstack([df[(df['idx'] == idx) & (df['IgM'] < 1) & (df['IgG'] < 10)]['get_date_at'], '2050-01-01']))

In [ ]:
np.vectorize(ImmGM_no)(No_immun_memory2['idx'])

array(['2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-05-20', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2020-05-26',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-05-15', '2050-01-01', '2050-01-01',
       '2020-05-21', '2020-06-04', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-05-24', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2020-05-27',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-05-26', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2020-06-16',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2020-05-28',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-05-29', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-05-30', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-05-29', '2050-01-01', '2020-06-08', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-06-11', '2050-01-01', '2020-06-05', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-06-14', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-06-18', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-06-02', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2020-06-16',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-06-04', '2020-06-04', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-06-05', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-06-10', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-06-10', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-06-09', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-06-12', '2050-01-01', '2020-06-11', '2050-01-01',
       '2050-01-01', '2020-06-13', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2020-06-13', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2020-06-18', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2020-06-28', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01'], dtype='<U10')

In [ ]:
#Когда тест IgM < 1 & IgG > 10
No_immun_memory2['day_M_G'] = np.vectorize(ImmGM_no)(No_immun_memory2['idx'])

In [ ]:
No_immun_memory2 = No_immun_memory2[No_immun_memory2['day_M_G'] != '2050-01-01']

In [ ]:
No_immun_memory2 = No_immun_memory2[No_immun_memory2['day_M_G'] > No_immun_memory2['test_day_M']]

In [ ]:
No_immun_memory2['idx'].unique()

array([169796, 213164, 213953, 254444])

In [ ]:
pd.DataFrame(No_immun_memory2['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/No_immun_memory2.xlsx')

Lost, группа потерянных из наблюдения

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
#из Acute illness те, кто выходят из наблюдения

df = df[df['idx'].isin(Acute_illness2)]
df = df[~df['idx'].isin(Immun_memory2['idx'])]
df = df[~df['idx'].isin(No_immun_memory2['idx'])]

In [ ]:
Lost2 = pd.DataFrame(df, columns=['idx'])

In [ ]:
Lost2['idx'].unique().shape

(787,)

In [ ]:
pd.DataFrame(Lost2['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Lost2.xlsx')